management:
  metrics:
    export:
      newrelic:
        account-id: 3080881
        api-key: NRAK-EV244RQ2XVR3IOH9AM2RDR88M97
        enabled: false

spring:
  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: update
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/company-manager
    username: postgres
    password: root
    driverClassName: org.postgresql.Driver