management:
  metrics:
    export:
      newrelic:
        account-id: 3080881
        api-key: NRAK-EV244RQ2XVR3IOH9AM2RDR88M97
        enabled: false

spring:
  jpa:
    database: MYSQL
    show-sql: false
    hibernate:
      ddl-auto: update
  datasource:
    platform: org.hibernate.dialect.MySQL5InnoDBDialect
    url: jdbc:mysql://localhost:3306/company-manager
    username: root
    password: root_1234
    driverClassName: com.mysql.cj.jdbc.Driver